config/routes.rb
VkContentManager::Application.routes.draw do

  devise_for :admins

  resources :groups, except: [ :edit, :update ] do
    get :get_people
  end
  resources :publics, except: [ :edit, :update ]
  resources :posts
  resources :accounts do
  	get :show_unlock_popup
  	post :unlock
  end
  resources :invite_templates

  root to: 'accounts#index'
end

app/models/public.rb
#encoding: utf-8

class Public < ActiveRecord::Base

  LOGIN_URL = 'https://vk.com'
  SCOPES = "notify,friends,photos,audio,video,docs,notes,pages,status,offers,questions,wall,groups,messages,notifications,stats,ads,offline"
  TARGET_URL = "https://oauth.vk.com/authorize?client_id=3409136&scope=#{SCOPES}&redirect_uri=http://oauth.vk.com/blank.html&display=wap&response_type=token"
  VK_API_BASE_URL = "https://api.vk.com/method/"

  attr_accessible \
    :avatar,
    :account_id,
    :closed,
    :name,
    :short_name,
    :vk_id

  belongs_to :account

  has_many :schedules

  has_many :posts

  mount_uploader :avatar, GroupAvatarUploader

  after_create :set_vk_data

  validates :vk_id, :uniqueness => true

  def vk_get_send_group_stats_request
    method = "groups.getMembers"
    group_id = vk_id
    query_ops = "gid=#{group_id}"

    access_token = Account.first.access_token
    target_url = "#{VK_API_BASE_URL}#{method}?#{query_ops}&access_token=#{access_token}"

     # puts "[RESULT URL] target_url: #{target_url}"

    RestClient.get(target_url)
  end

  def vk_get_group_stats
    response = JSON.parse(vk_get_send_group_stats_request.body)['response']
    count, users_list = response['count'], response['users']

     # puts "[RESULT URL] count: #{count}"
     # puts "[RESULT URL] users_list: #{users_list}"

    [ count, users_list ]
  end

  def today_schedule
    schedules.between_dates(Time.zone.now.midnight, Time.zone.now.midnight + 1.day).first
  end

  def next_post
    #today_schedule.scheduled_posts.order('post_date_time ASC').first
    ScheduledPost.order('post_date_time ASC').first
  end

  private

  def set_vk_data
  	method = "groups.getById"
    group_id = vk_id
    ops = "gid=#{group_id}"

    access_token = Account.first.access_token
    target_url = "#{VK_API_BASE_URL}#{method}?#{ops}&access_token=#{access_token}"

     # puts "[RESULT URL] target_url: #{target_url}"

    response = JSON.parse(RestClient.get(target_url).body)['response'][0]

     # puts "[RESULT URL] response: #{response.inspect}"

    self.name = response['name']
    self.short_name = response['screen_name']
    self.closed = response['is_closed'] == 0 ? true : false
    self.remote_avatar_url = response['photo_big']

    save!
  end
end

app/controllers/publics_controller.rb
# encoding: utf-8

class PublicsController < ApplicationController

  before_filter :authenticate_admin!, :set_active_tab

  def index
    @publics = Public.scoped
  end

  def show
    @public = Public.find(params[:id])
  end

  def new
    @public = Public.new
  end

  def create
    @public = Public.new(params[:public])

    if @public.save
      redirect_to publics_url, notice: 'Паблик успешно добавлен!'
    else
      render action: "new"
    end
  end

  def destroy
    @public = Public.find(params[:id])
    @public.destroy

    redirect_to publics_url
  end

  private

  def set_active_tab
    @active_tab = 'publics'
  end  
end

app/views/publics/_details.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel">Modal header</h3>
</div>
<div class="modal-body">
  <p>One fine body…</p>
</div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  <button class="btn btn-primary">Save changes</button>
</div>

app/views/publics/_form.html.erb
<%= form_for(@public) do |f| %>
  <% if @public.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@public.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @public.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vk_id, 'ID паблика' %><br />
    <%= f.text_field :vk_id %>
  </div>

  <div class="field">
    <%= f.label :account_id, 'Admin Аккаунт' %><br />
    <%= f.select :account_id, Account.scoped.collect { |a| [ a.full_name, a.id ] } %>
  </div>  

  <%= f.submit 'Сохранить', class: 'btn btn-info btn-small' %>
<% end %>

app/views/publics/_item.html.erb
<li class="span3">
  <div class="thumbnail">
    <%= link_to '#', class: "review" do %>
    	<p class='preview_container'>
    	  <% if post[:photo].present? %>
          <%= image_tag post[:photo][:big] %>
        <% else %>
          <%= post[:text] %>
        <% end %>
      </p>
    <% end %>
    <div class="caption">
      <h6><%= post[:date].strftime("%Y-%m-%d, %H:%M") %></h6>
      <p>
      	<%= link_to '#', class: 'btn btn-mini btn-primary' do %>
          <i class='icon-eye-open'></i> Паблиш
        <% end %>
        <%= link_to '#', class: 'btn btn-mini btn-primary review', role: "button", "data-toggle" => "modal" do %>
          <i class='icon-eye-open'></i> Посмотреть
        <% end %>
      </p>
    </div>
  </div>
</li>

app/views/publics/index.html.erb
<h4>Паблики</h4>

<%= link_to 'Добавить', new_public_path, class: 'btn btn-mini btn-primary' %><br />

<div class="row-fluid"><br />
  <ul class="thumbnails">
    <% @publics.each do |public| %>
      <li class="span3">
        <div class="thumbnail">
          <%= link_to public_url(public) do %>
            <%= image_tag public.avatar.url(:thumb) %>
          <% end %>
          <div class="caption">
            <h6>
              <%= public.name %><br />
              ID: <%= public.vk_id %>
            </h6>
            <p>
              Admin name: <br />
              <%= public.account.full_name %>
            </p>
            <p>
              <%= link_to "http://vk.com/#{public.short_name}", class: 'btn btn-mini btn-info' do %>
                <i class='icon-eye-open'></i> на VK
              <% end %>
              <%= link_to public_url(public), method: :delete, class: 'btn btn-mini btn-danger' do %>
                <i class='icon-remove'></i>
              <% end %>
            </p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/publics/new.html.erb
<h4>Добавление паблика</h4>

<%= render 'form' %>

<%= link_to 'Назад', publics_path, class: 'btn btn-info btn-mini' %>

app/views/publics/show.html.erb
<%= content_for :javascript_code do %>
  GroupsManagement.initialize();
<% end %>

<%= link_to 'Назад', groups_path, class: 'btn btn-info btn-mini' %><br /><br />

<div class="well">
  <%= image_tag @group.avatar.url(:detail) %>
  <div class="caption">
    <h6><%= @group.name %></h6>
    <p><strong><%= @posts.count %></strong> <%= Russian.p(@posts.count, "пост", "постa", "постов") %></p>
  </div>
</div>

<div class='group_posts'>
  <div class="row-fluid"><br />
	<ul class="thumbnails">	
      <% @posts.each do |post| %>
        <%= render 'groups/item', post: post %>
	  <% end %>
	</ul>
  </div>
</div>