config/routes.rb
VkContentManager::Application.routes.draw do

  devise_for :admins

  resources :groups, except: [ :edit, :update ] do
    get :get_people
  end
  resources :publics, except: [ :edit, :update ]
  resources :posts
  resources :accounts do
  	get :show_unlock_popup
  	post :unlock
  end
  resources :invite_templates

  root to: 'accounts#index'
end

app/models/group.rb
#encoding: utf-8

class Group < ActiveRecord::Base

  TARGET_URL = "https://oauth.vk.com/authorize?client_id=3409136&scope=friends,groups,messages,offline,stats,wall,notify&redirect_uri=http://oauth.vk.com/blank.html&display=wap&response_type=token"
  VK_API_BASE_URL = "https://api.vk.com/method/"

  attr_accessible \
    :avatar,
    :name,
    :short_name,
    :vk_id,
    :gid,
    :closed

  has_many :posts
  has_many :people, class_name: 'InvitedPerson'

  mount_uploader :avatar, GroupAvatarUploader

  after_create :set_vk_data

  validates :vk_id, :uniqueness => true

  def vk_get_send_group_stats_request
    method = "groups.getMembers"
    group_id = '48529852'
    query_ops = "gid=#{group_id}"

    access_token = Account.first.access_token
    target_url = "#{VK_API_BASE_URL}#{method}?#{query_ops}&access_token=#{access_token}"

     # puts "[RESULT URL] target_url: #{target_url}"

    RestClient.get(target_url)
  end

  def vk_get_group_stats
    response = JSON.parse(vk_get_send_group_stats_request.body)['response']
    count, users_list = response['count'], response['users']

     # puts "[RESULT URL] count: #{count}"
     # puts "[RESULT URL] users_list: #{users_list}"

    [ count, users_list ]
  end

  def vk_is_member_of_group?(user_id, group_id)
    method = "groups.isMember"
    query_ops = "gid=#{group_id}&uid=#{user_id}"

    access_token = Account.first.access_token
    target_url = "#{VK_API_BASE_URL}#{method}?#{query_ops}&access_token=#{access_token}"

     # puts "[RESULT URL] target_url: #{target_url}"

    response = JSON.parse(RestClient.get(target_url).body)['response']
    response.to_s == '1'
  end

  def vk_wall_get_content_for_group
    method = "wall.get"
    query_ops = "owner_id=-#{self.gid}&count=#{10}"

    access_token = Account.first.access_token
    target_url = "#{VK_API_BASE_URL}#{method}?#{query_ops}&access_token=#{access_token}"

     # puts "[RESULT URL] target_url: #{target_url}"

    resp = RestClient.get(target_url)

     # puts "[RESULT URL] resp: #{resp.inspect}"
     Rails.logger.info "----------------[RESULT URL] resp: #{resp.inspect}"

    JSON.parse(resp.body)['response']
  end

  def vk_parse_last_ten_posts_from_group
    html_posts = []

    Rails.logger.info "----------ID-----------------#{self.id}"

    posts = vk_wall_get_content_for_group[1..-1]

    posts.each do |post|
       # puts "[RESULT] post: #{post}"

      if post['date'].present?
        date = Time.at(post['date'].to_i).in_time_zone
        text = post['text']
        post_id = "#{self.vk_id}_#{post['id']}"

        attach = post['attachments']
        if attach.present? && attach[0].present? && attach[0]['photo'].present?
          photo_ops = attach[0]['photo']

          big_photo = photo_ops['src_xbig'] if photo_ops['src_xbig'].present?
          big_photo = photo_ops['src_big'] if big_photo.blank? && photo_ops['src_big'].present?
          small_photo = photo_ops['src_small'] if photo_ops['src_small'].present?
        end

        parsed_post = {
          date: date,
          post_id: post_id
        }

        parsed_post[:text] = text
        parsed_post[:photo] = {
            big: big_photo,
            small: small_photo
        } if big_photo.present?

        html_posts << parsed_post
      end
    end

    html_posts
  end


  ############################################
  # Get people                               #
  ############################################

  def get_people
    method = "groups.getMembers"

    ops = {
      gid: gid,
      count: 1000,
      offset: 0,
      sort: 'id_asc'
    }.to_param

    puts "[RESULT URL] ops: #{ops}"

    access_token = Account.first.access_token

    puts "[RESULT URL] access_token: #{access_token}"

    target_url = "#{Public::VK_API_BASE_URL}#{method}?#{ops}&access_token=#{access_token}"

    puts "[RESULT URL] target_url: #{target_url}"

    uri = URI.encode(target_url.strip)

    resp = RestClient.get(uri)

    puts "[RESULT URL] JSON.parse(resp.body): #{JSON.parse(resp.body)}"

    response = JSON.parse(resp.body)['response']

    count_of_members = response['count'].to_i

    response['users'].each do |user_id|

      puts "[RESULT URL] user_id: #{user_id}"

      is_member = is_member?(user_id)
      in_black_list = false

      people.create!(
        vk_id: user_id,
        invited: false,
        in_black_list: in_black_list,
        is_member: is_member        
      ) unless InvitedPerson.find_by_vk_id(user_id).present?
    end

    count_of_requests = count_of_members / 1000

    count_of_members.times do |i|

      sleep 0.1

      puts "[RESULT URL] count_of_members: #{i}"

      method = "groups.getMembers"

      ops = {
        gid: gid,
        count: 1000,
        offset: 1000 * i,
        sort: 'id_asc'
      }.to_param

      puts "[RESULT URL] ops: #{ops}"

      access_token = Account.first.access_token

      puts "[RESULT URL] access_token: #{access_token}"

      target_url = "#{Public::VK_API_BASE_URL}#{method}?#{ops}&access_token=#{access_token}"

      puts "[RESULT URL] target_url: #{target_url}"

      uri = URI.encode(target_url.strip)

      resp = RestClient.get(uri)

      puts "[RESULT URL] JSON.parse(resp.body): #{JSON.parse(resp.body)}"

      response = JSON.parse(resp.body)['response']

      count_of_members = response['count'].to_i

      response['users'].each do |user_id|

        puts "[RESULT URL] user_id: #{user_id}"

        is_member = is_member?(user_id)
        in_black_list = false

        people.create!(
          vk_id: user_id,
          invited: false,
          in_black_list: in_black_list,
          is_member: is_member        
        ) unless InvitedPerson.find_by_vk_id(user_id).present?
      end
    end
  end

  def is_member?(user_id)
    sleep 0.1

    method = "groups.isMember"

    ops = {
      gid: Public.first.vk_id,
      uid: user_id
    }.to_param

    puts "[RESULT URL] ops: #{ops}"

    access_token = Account.first.access_token

    puts "[RESULT URL] access_token: #{access_token}"

    target_url = "#{Public::VK_API_BASE_URL}#{method}?#{ops}&access_token=#{access_token}"

    puts "[RESULT URL] target_url: #{target_url}"

    uri = URI.encode(target_url.strip)

    resp = RestClient.get(uri)

    puts "[RESULT URL] JSON.parse(resp.body): #{JSON.parse(resp.body)}"

    response = JSON.parse(resp.body)['response'][0]

    response.to_i == 1 ? true : false
  end

  ############################################
  # Invite people                            #
  ############################################

  def invite_people
    Account.update_all(invite_counter: 0)

    prepare_people.each do |person|
      account = Account.next

      template = InviteTemplate.next

      method = "messages.send"

      invited_person = person

      access_token = account.access_token

      ops = {
        uid: invited_person[0],
        title: template.title + " #{invited_person[1]}",
        message: ActionView::Base.full_sanitizer.sanitize(template.content).gsub("&nbsp;", ""),
        content_type: 'text/plain',
        attachment: "photo207657525_302085012"
      }

      puts "[RESULT URL] ops: #{ops}"

      target_url = "#{Public::VK_API_BASE_URL}#{method}?access_token=#{access_token}"

      puts "[RESULT URL] target_url: #{target_url}"

      uri = URI.encode(target_url.strip)

      resp = RestClient.post target_url, ops

      result = JSON.parse(resp.body)

      puts "[RESULT URL] JSON.parse(resp.body): #{result}"

      inv_person = InvitedPerson.find_by_vk_id(invited_person[0])

      if result['error'].present? 
        code = result['error']['error_code']

        inv_person.update_attributes(
          template_id: template.id,
          public_id: 4,
          error_code: code
        )
      else
        inv_person.update_attributes(
          template_id: template.id,
          public_id: 4
        )
      end

      template.increment_counter!
      account.increment_counter!
      inv_person.mark_as_invited!

      sleep 1
    end
  end

  def prepare_people
    real_count = 0
    access_token = Account.not_blocked.first.access_token
    pr_people = []

    person_id = InvitedPerson.next.id

    while real_count < (Account.not_blocked.count * 20) do
      person = InvitedPerson.not_invited.in_target_category.find_by_id(person_id)

      if person.present?
        data = get_person_data(person.vk_id, access_token)
        first_name, sex, can_write, relation, city, birth, online = data[0], data[1], data[2], data[3], data[4], data[5], data[6]

        puts "[RESULT URL] first_name: #{first_name}, sex: #{sex}, can_write: #{can_write}, relation: #{relation}, city: #{city}, birth: #{birth}, online: #{online}"

        success = city.to_i == 60 && sex.to_i == 1 && can_write.to_i == 1 && (birth.present? && birth.split('.')[2].to_i < 1994)

        if success
          if online.to_i == 0
            puts "[RESULT URL] success: #{success.present?}"
            pr_people << [ person.vk_id, first_name ]
            real_count += 1 
          end
        else
          person.update_attribute(:not_in_target_category, true)
        end
      end 
       
      person_id += 1

      puts "[RESULT URL] real_count: #{real_count}"

      sleep 0.3
    end

    puts "[RESULT URL] real_count: #{real_count}, pr_people: #{pr_people}"

    pr_people
  end

  def get_person_data(person_vk_id, access_token)
    method = "users.get"

    ops = {
      uids: person_vk_id
    }.to_param

    puts "[RESULT URL] ops: #{ops}"

    target_url = "#{Public::VK_API_BASE_URL}#{method}?#{ops}&access_token=#{access_token}&fields=first_name,sex,can_write_private_message,relation,city,online,bdate"

    puts "[RESULT URL] target_url: #{target_url}"

    uri = URI.encode(target_url.strip)

    resp = RestClient.get(uri)

    puts "[RESULT URL] JSON.parse(resp.body): #{JSON.parse(resp.body)}"

    response = JSON.parse(resp.body)['response'][0]

app/controllers/groups_controller.rb
# encoding: utf-8

class GroupsController < ApplicationController

  before_filter :authenticate_admin!, :set_active_tab

  def index
    @groups = Group.scoped
  end

  def show
    @group = Group.find(params[:id])
    @posts = [] # @group.vk_parse_last_ten_posts_from_group
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(params[:group])

    if @group.save
      redirect_to groups_url, notice: 'Группа успешно добавлена!'
    else
      render action: "new"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to groups_url
  end

  def get_people
    @group = Group.find(params[:group_id])
    @group.get_people

    redirect_to group_url(@group)
  end

  private

  def set_active_tab
    @active_tab = 'generators'
  end
end

app/views/groups/_details.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel">Modal header</h3>
</div>
<div class="modal-body">
  <p>One fine body…</p>
</div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  <button class="btn btn-primary">Save changes</button>
</div>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vk_id, 'ID группы' %><br />
    <%= f.text_field :vk_id %>
  </div>

  <%= f.submit 'Сохранить', class: 'btn btn-info btn-small' %>
<% end %>

app/views/groups/_item.html.erb
<%
  ops = {
    vk_post_id: post[:post_id],
    group_id: post[:group_id],
    photo: post[:photo].present? ? post[:photo][:big] : nil,
    text: post[:text]}
%>

<li class="span3">
  <div class="thumbnail">
    <%= link_to '#', class: "review" do %>
    	<p class='preview_container'>
          <%= link_to new_post_url(ops), remote: true do %>
      	  <% if post[:photo].present? %>
            <%= image_tag post[:photo][:big] %>
          <% else %>
            <%= post[:text].html_safe %>
          <% end %>
        <% end %>
      </p>
    <% end %>
    <div class="caption">
      <h6><%= post[:date].strftime("%Y-%m-%d, %H:%M") %></h6>
        <ul style='height: 20px; margin-bottom: 10px;'>
          <% publics = Public.select{ |p| p.posts.where(vk_post_id: post[:post_id]).present? } %>
          <% publics.each do |p| %>
            <li><%= p.name %></li>
          <% end %>
        </ul>
      <p>
      	<%= link_to new_post_url(ops), remote: true, class: 'btn btn-mini btn-primary' do %>
          <i class='icon-eye-open'></i> Паблиш
        <% end %>
        <%= link_to new_post_url(ops), remote: true, class: 'btn btn-mini btn-primary' do %>
          <i class='icon-eye-open'></i> Посмотреть
        <% end %>
      </p>
    </div>
  </div>
</li>

app/views/groups/get_people.html.erb
<h4>Подписчики</h4>

<div class="row-fluid"><br />
  <ul class="thumbnails">
    <% @people.each do |people| %>
      <li>
        ID: <%= people.vk_id %>
      </li>
    <% end %>
  </ul>
</div>

app/views/groups/index.html.erb
<h4>Генераторы</h4>

<%= link_to 'Добавить', new_group_path, class: 'btn btn-mini btn-primary' %><br />

<div class="row-fluid"><br />
  <ul class="thumbnails">
    <% @groups.each do |group| %>
      <li class="span3">
        <div class="thumbnail">
          <%= link_to group_url(group) do %>
            <%= image_tag group.avatar.url(:thumb) %>
          <% end %>
          <div class="caption">
            <h6><%= group.name %></h6>
            <p>
              <%= link_to group_get_people_url(group), class: 'btn btn-mini btn-info' do %>
                <i class='icon-eye-open'></i> Выгрузить Подписчиков
              <% end %>
              <%= link_to group_url(group), class: 'btn btn-mini btn-primary' do %>
                <i class='icon-eye-open'></i> Посты
              <% end %>
              <%= link_to "http://vk.com/#{group.short_name}", class: 'btn btn-mini btn-info' do %>
                <i class='icon-eye-open'></i> на VK
              <% end %>
              <%#= link_to group_url(group), method: :delete, class: 'btn btn-mini btn-danger' do %>
               <!-- <i class='icon-remove'></i> -->
              <%# end %>
            </p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/groups/new.html.erb
<h4>Добавление группы</h4>

<%= render 'form' %>

<%= link_to 'Назад', groups_path, class: 'btn btn-info btn-mini' %>

app/views/groups/show.html.erb
<%= link_to 'Назад', groups_path, class: 'btn btn-info btn-mini' %><br /><br />

<div class="well">
  <%= image_tag @group.avatar.url(:detail) %>
  <div class="caption">
    <h6><%= @group.name %></h6>
    <p><strong><%= @group.people.count %></strong> <%= Russian.p(@posts.count, "подписчик", "подписчикa", "подписчиков") %></p>
  </div>
</div>

<div class='group_posts'>
  <div class="row-fluid"><br />
	<ul class="thumbnails">
      <% @posts.each do |post| %>
        <%= render 'groups/item', post: post %>
	  <% end %>
	</ul>
  </div>
</div>