config/routes.rb
VkContentManager::Application.routes.draw do

  devise_for :admins

  resources :groups, except: [ :edit, :update ] do
    get :get_people
  end
  resources :publics, except: [ :edit, :update ]
  resources :posts
  resources :accounts do
  	get :show_unlock_popup
  	post :unlock
  end
  resources :invite_templates

  root to: 'accounts#index'
end

app/models/invite_template.rb
class InviteTemplate < ActiveRecord::Base

  set_table_name :templates

  attr_accessible :content, :image, :title, :invite_counter

  mount_uploader :image, InviteTemplateUploader

  def increment_counter!
  	update_attribute(:invite_counter, invite_counter + 1)
  end

  class << self
    def next
      where(invite_counter: minimum("invite_counter")).first
    end
  end
end

app/controllers/invite_templates_controller.rb
class InviteTemplatesController < ApplicationController
  # GET /templates
  # GET /templates.json
  def index
    @templates = InviteTemplate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @templates }
    end
  end

  # GET /templates/1
  # GET /templates/1.json
  def show
    @template = InviteTemplate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @template }
    end
  end

  # GET /templates/new
  # GET /templates/new.json
  def new
    @template = InviteTemplate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @template }
    end
  end

  # GET /templates/1/edit
  def edit
    @template = InviteTemplate.find(params[:id])
  end

  # POST /templates
  # POST /templates.json
  def create
    @template = InviteTemplate.new(params[:invite_template])

    respond_to do |format|
      if @template.save
        format.html { redirect_to @template, notice: 'Template was successfully created.' }
        format.json { render json: @template, status: :created, location: @template }
      else
        format.html { render action: "new" }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /templates/1
  # PUT /templates/1.json
  def update
    @template = InviteTemplate.find(params[:id])

    respond_to do |format|
      if @template.update_attributes(params[:invite_template])
        format.html { redirect_to @template, notice: 'Template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /templates/1
  # DELETE /templates/1.json
  def destroy
    @template = InviteTemplate.find(params[:id])
    @template.destroy

    respond_to do |format|
      format.html { redirect_to invite_templates_url }
      format.json { head :no_content }
    end
  end
end

app/views/invite_templates/_form.html.erb
<%= form_for(@template, html: { multipart: true }) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, id: 'redactor_content' %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invite_templates/edit.html.erb
<h1>Editing template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', invite_templates_path %>

app/views/invite_templates/index.html.erb
<h1>Listing templates</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @templates.each do |template| %>
  <tr>
    <td><%= template.title %></td>
    <td><%= template.content %></td>
    <td><%= template.image %></td>
    <td><%= link_to 'Show', template %></td>
    <td><%= link_to 'Edit', edit_invite_template_path(template) %></td>
    <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Template', new_invite_template_path %>

app/views/invite_templates/new.html.erb
<h1>New template</h1>

<%= render 'form' %>

<%= link_to 'Back', invite_templates_path %>

app/views/invite_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @template.title %>
</p>

<p>
  <b>Content:</b>
  <%= raw @template.content %>
</p>

<p>
  <%= image_tag @template.image.url %>
</p>


<%= link_to 'Edit', edit_invite_template_path(@template) %> |
<%= link_to 'Back', invite_templates_path %>