config/routes.rb
VkContentManager::Application.routes.draw do

  devise_for :admins

  resources :groups, except: [ :edit, :update ] do
    get :get_people
  end
  resources :publics, except: [ :edit, :update ]
  resources :posts
  resources :accounts do
  	get :show_unlock_popup
  	post :unlock
  end
  resources :invite_templates

  root to: 'accounts#index'
end

app/models/account.rb
#encoding: utf-8

class Account < ActiveRecord::Base

  LOGIN_URL = 'https://vk.com'
  SCOPES = "notify,friends,photos,audio,video,docs,notes,pages,status,offers,questions,wall,groups,messages,notifications,stats,ads,offline"
  TARGET_URL = "https://oauth.vk.com/authorize?client_id=3409136&scope=#{SCOPES}&redirect_uri=http://oauth.vk.com/blank.html&display=wap&response_type=token"
  VK_API_BASE_URL = "https://api.vk.com/method/"

  attr_accessible \
    :vk_id,
    :phone,
    :first_name,
    :last_name,
    :avatar,
    :blocked,
    :password,
    :access_token,
    :invite_counter,
    :unlock

  attr_accessor :unlock

  has_many :publics

  mount_uploader :avatar, AccountAvatarUploader

  validates :vk_id, :phone,
    :presence => true,
    :uniqueness => true

  after_create :add_vk_data
  after_update :add_vk_data, if: 'unlock.present?'

  scope :blocked, where(blocked: true)
  scope :not_blocked, where(blocked: false)

  def increment_counter!
    update_attribute(:invite_counter, invite_counter + 1)
  end

  def new_password
    SecureRandom.hex(4)
  end

  class << self
    def next
      not_blocked.where(invite_counter: not_blocked.minimum("invite_counter")).first
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def vk_login
    client = Mechanize.new
    client.get(LOGIN_URL)
    form = client.page.forms.first

 # Rails.logger.info "[ LOGGER 1 ] phone: #{phone.inspect}"

    form.email = phone

 # Rails.logger.info "[ LOGGER 1 ] password: #{password.inspect}"

    form.pass = password
    form.submit

    client
  end

  def vk_get_perms_page
    client = vk_login
    client.get(TARGET_URL)

     # Rails.logger.info "[ LOGGER 1 - 3 ] client.page.forms.first: #{client.page.forms.first.inspect}"
    form = client.page.forms.first
    form.submit

    client
  end

  def vk_get_creds(client)
   # Rails.logger.info "[ LOGGER 2 - 1 ] client.page: #{client.page.inspect}"

   # Rails.logger.info "[ LOGGER 2 - 2 ] client.page.uri: #{client.page.uri.inspect}"

   # Rails.logger.info "[ LOGGER 2 - 3 ] client.page.uri.to_json: #{client.page.uri.to_json.inspect}"

    response_ops = JSON.parse(client.page.uri.to_json)
   # Rails.logger.info "[ LOGGER 2 - 4 ] response_ops: #{response_ops.inspect}"
    fragments = response_ops['fragment'].split('&')
    vk_parse_response(fragments)
  end

  def vk_parse_response(fragments)
    access_token, user_id, expires_in = nil, nil, nil

    fragments.each do |fragment|
      if fragment.include?('access_token')
        access_token = fragment.split('=')[1]
      elsif fragment.include?('user_id')
        user_id = fragment.split('=')[1]
      elsif fragment.include?('expires_in')
        expires_in = fragment.split('=')[1]
      end
    end

    [ access_token, user_id, expires_in ]
  end

  def locked?
    method = "users.get"
    target_url = "#{VK_API_BASE_URL}#{method}?access_token=#{access_token}&uids=#{vk_id}"

    puts "[RESULT URL] target_url: #{target_url}"

    uri = URI.encode(target_url.strip)

    resp = RestClient.get(uri)

    puts "[RESULT URL] JSON.parse(resp.body): #{JSON.parse(resp.body)}"

    response = JSON.parse(resp.body)
    response['error'].present? ? true : false
  end

  private

  def vk_user_details_request
    method = "users.get"
    uids = vk_id
    query_ops = "uids=#{uids}"
    client = vk_get_perms_page
    access_token = vk_get_creds(client).first
    target_url = "#{VK_API_BASE_URL}#{method}?#{query_ops}&access_token=#{access_token}"

    client.get(target_url)
  end

  def add_vk_data
    client = vk_get_perms_page
    access_token = vk_get_creds(client).first
    self.access_token = access_token

    method = "users.get"
    query_ops = "uids=#{vk_id}"
    fields = "first_name, last_name, photo_big"

    target_url = "#{VK_API_BASE_URL}#{method}?#{query_ops}&access_token=#{access_token}&fields=#{fields}"

    response = client.get(target_url)

    data = JSON.parse(response.body)['response'][0]

    self.first_name = data['first_name']
    self.last_name = data['last_name']
    self.remote_avatar_url = data['photo_big']

    self.save!
  end
end

app/controllers/accounts_controller.rb
# encoding: utf-8

class AccountsController < ApplicationController

  before_filter :authenticate_admin!, :set_active_tab

  def index
    @accounts = Account.scoped
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(params[:account])

    if @account.save
      redirect_to accounts_url, notice: 'Паблик успешно добавлен!'
    else
      render action: "new"
    end
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    redirect_to accounts_url
  end

  def show_unlock_popup
    @account = Account.find(params[:account_id])
  end

  def unlock
    @account = Account.find(params[:account_id])
    @account.update_attributes(password: params[:password], unlock: true)
  end

  private

  def set_active_tab
    @active_tab = 'accounts'
  end  
end

app/views/accounts/_details.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel">Modal header</h3>
</div>
<div class="modal-body">
  <p>One fine body…</p>
</div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  <button class="btn btn-primary">Save changes</button>
</div>

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vk_id, 'ID пользователя' %><br />
    <%= f.text_field :vk_id %>
  </div>

  <div class="field">
    <%= f.label :phone, 'Телефон пользователя' %><br />
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :password, 'Пароль пользователя' %><br />
    <%= f.password_field :password %>
  </div>

  <%= f.submit 'Сохранить', class: 'btn btn-info btn-small' %>
<% end %>

app/views/accounts/_item.html.erb
<% 
  locked = account.locked?
  account.update_attribute(:blocked, locked ? true : false)
%>
<li class="span3" id="<%= dom_id(account) %>">
  <div class="thumbnail">
    <%= link_to account_url(account) do %>
      <%= image_tag account.avatar.url(:thumb) %>
    <% end %>
    <div class="caption <% if locked %>blocked_account<% end %>">
      <h6>
        <%= account.full_name %><br />
        ID: <%= account.vk_id %><br />
        Моб: <%= account.phone %><br />
      </h6>
      <br />
      <p>
        <%= link_to "http://vk.com/id#{account.vk_id}", class: 'btn btn-mini btn-info' do %>
          <i class='icon-eye-open'></i> на VK
        <% end %>
        <% if locked %>
          <%= link_to account_show_unlock_popup_url(account), remote: true, class: 'btn btn-mini btn-success' do %>
            <i class='icon-eye-open'></i> Разблокировать
          <% end %>
        <% end %>
      </p>
    </div>
  </div>
</li>

app/views/accounts/_unlock_form.html.erb
<% 
  new_password = @account.new_password
%>

<div class='well unlock_block'>
  <button type="button" class="close btn pull-right" data-dismiss="modal" aria-hidden="true">Закрыть</button>
  <h4 class='gray'>Для разблокировки аккаунта:</h4><br />
  <ul>
    <li>
      1: Вставьте в телефон сим-карту с номером <strong>"<%= @account.phone %>"</strong>
      и дождитесь пока телефон окончательно включится
    </li>
    <li>
      2: Пройдите по следующему урлу <%= link_to "Пройти", "http://vk.com/id#{@account.vk_id}", "target" => "_blank", class: 'btn btn-info btn-small' %>
      и убедитесь что в текущий момент Вы не под каким аккаунтом не залогинены.
    </li>
    <li>
      3: В поле ввода <strong>"Телефон или email"</strong> введите <strong><%= @account.phone %></strong>
    </li>
    <li>
      4: В поле ввода <strong>"Пароль"</strong> введите <strong><%= @account.password %></strong>
      и нажмите <strong>"Войти"</strong>
    </li>    
    <li>
      5: В открывшейся странице внизу на найдите кнопку <strong>"Отправить"</strong> и нажмите ее.
      Через некоторое время Вам на телефон придет код.
    </li>
    <li>
      6: Введите его в соответствующее поле для кода.
      Затем в поле ввода нового пароля введите вот этот пароль <strong>"<%= new_password %>"</strong>
      и нажмите кнопку, расположенную ниже пароля.
      После этого Вы попадете на страницу разблокированного аккаунта.
      Сразу как Вы на нее попадете - вернитесь на форму разблокировки и нажмите кнопку <strong>"Разблокировать"</strong>
    </li>
  </ul><br />
  <%= form_for(@account, url: account_unlock_url(account_id: @account.id), method: :post, remote: true) do |f| %>
    <%= hidden_field_tag :password, new_password %>
    <%= f.submit 'Разблокировать', class: 'btn btn-success btn-small pull-right' %>
  <% end %>
</div>

app/views/accounts/index.html.erb
<h4>Аккаунты</h4>

<%= link_to 'Добавить', new_account_path, class: 'btn btn-mini btn-primary' %><br />

<div class="row-fluid"><br />
  <ul class="thumbnails">
    <% @accounts.each do |account| %>
      <%= render 'accounts/item', account: account %>
    <% end %>
  </ul>
</div>

app/views/accounts/new.html.erb
<h4>Добавление аккаунта</h4>

<%= render 'form' %>

<%= link_to 'Назад', accounts_path, class: 'btn btn-info btn-mini' %>

app/views/accounts/show.html.erb
<%= content_for :javascript_code do %>
  GroupsManagement.initialize();
<% end %>

<%= link_to 'Назад', groups_path, class: 'btn btn-info btn-mini' %><br /><br />

<div class="well">
  <%= image_tag @group.avatar.url(:detail) %>
  <div class="caption">
    <h6><%= @group.name %></h6>
    <p><strong><%= @posts.count %></strong> <%= Russian.p(@posts.count, "пост", "постa", "постов") %></p>
  </div>
</div>

<div class='group_posts'>
  <div class="row-fluid"><br />
	<ul class="thumbnails">	
      <% @posts.each do |post| %>
        <%= render 'groups/item', post: post %>
	  <% end %>
	</ul>
  </div>
</div>

app/views/accounts/show_unlock_popup.js.erb
$( '#custom_modal' ).modal().html("<%= escape_javascript(
  render('accounts/unlock_form')
) %>");

app/views/accounts/unlock.js.erb
$( '#custom_modal' ).modal('hide').html("");
$( "#<%= dom_id(@account) %>" ).replaceWith("<%= escape_javascript(
  render('accounts/item', account: @account)
) %>");